import type { Metadata } from "next";
import { Inter, Fira_Sans_Condensed } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/components/provider/toaster";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

const inter = Inter({
  subsets: ["latin"],
});

const Fira = Fira_Sans_Condensed({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-Fira", // Añadir esta línea
});

export const metadata: Metadata = {
  title: "Erase - Docs and Diagrams for",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/logo.sin.png" type="image/x-icon"  />
      </head>

      <body className={`${inter.className} ${Fira.variable}`}>
        <SessionProvider session={session}>
          <ToastProvider />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
