import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "./ConvexClientProvider";
import ToastProvider from "@/components/provider/toaster";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Erase - Docs and Diagrams for",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/logo.svg" type="image/x-icon" />
      </head>

      <body className={inter.className}>
        <ConvexClientProvider>
          <ToastProvider />
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  );
}
